app = "mastodon-neon"

[deploy]
  release_command = "bundle exec rails db:setup"

[env]
  RAILS_ENV = "production"
  DB_HOST=''
  DB_USER=''
  DB_NAME=''
  DB_PASS=''
  DB_PORT = ''

  REDIS_HOST = ""
  REDIS_PORT = ""
  REDIS_PASSWORD = ""